name: CI

# Controls when the workflow will run
on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a job called "build_on_linux"
  build_on_linux:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          ech Add other actions to build,
          echo test, and deploy your project.

  # This workflow contains a job called "build_on_windows"
  build_on_windows:
    # The type of runner that the job will run on
    runs-on: windows-latest
    if: ${{ success() }}
    needs: [build_on_linux]
    
    steps:
      - name: Run a multi-line script on Windows
        run: |
          echo "Hello, GitHub Actions"
          powershell -Command "Get-Date"
